from matplotlib import pyplot as plt

# load data
import pickle
with open('3D_lorenz.pkl','rb') as f:
    xout, tout, x_without_noise, euler_param, sim_param = pickle.load(f)

p0, = plt.plot(tout[0, :], xout[0, :, 0], label='time series 0')
p1, = plt.plot(tout[0, :], xout[1, :, 0], label='time series 1')
p2, = plt.plot(tout[0, :], xout[2, :, 0], label='time series 2')
p3, = plt.plot(tout[0, :], xout[3, :, 0], label='time series 3')
p4, = plt.plot(tout[0, :], xout[4, :, 0], label='time series 4')
p5, = plt.plot(tout[0, :], xout[5, :, 0], label='time series 5')
p6, = plt.plot(tout[0, :], xout[6, :, 0], label='time series 6')
p7, = plt.plot(tout[0, :], xout[7, :, 0], label='time series 7')
p8, = plt.plot(tout[0, :], xout[8, :, 0], label='time series 8')
p9, = plt.plot(tout[0, :], xout[9, :, 0], label='time series 9')
p10, = plt.plot(tout[0, :], xout[10, :, 0], label='time series 10')
plt.legend(handles = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10], bbox_to_anchor = (1.05, 1), loc = 2, borderaxespad = 0.)
plt.title('Lorenz oscillator (x\')')
plt.show()

p0, = plt.plot(tout[0, :], xout[0, :, 1], label='time series 0')
p1, = plt.plot(tout[0, :], xout[1, :, 1], label='time series 1')
p2, = plt.plot(tout[0, :], xout[2, :, 1], label='time series 2')
p3, = plt.plot(tout[0, :], xout[3, :, 1], label='time series 3')
p4, = plt.plot(tout[0, :], xout[4, :, 1], label='time series 4')
p5, = plt.plot(tout[0, :], xout[5, :, 1], label='time series 5')
p6, = plt.plot(tout[0, :], xout[6, :, 1], label='time series 6')
p7, = plt.plot(tout[0, :], xout[7, :, 1], label='time series 7')
p8, = plt.plot(tout[0, :], xout[8, :, 1], label='time series 8')
p9, = plt.plot(tout[0, :], xout[9, :, 1], label='time series 9')
p10, = plt.plot(tout[0, :], xout[10, :, 1], label='time series 10')
plt.legend(handles = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10], bbox_to_anchor = (1.05, 1), loc = 2, borderaxespad = 0.)
plt.title('Lorenz oscillator (y\')')
plt.show()

p0, = plt.plot(tout[0, :], xout[0, :, 2], label='time series 0')
p1, = plt.plot(tout[0, :], xout[1, :, 2], label='time series 1')
p2, = plt.plot(tout[0, :], xout[2, :, 2], label='time series 2')
p3, = plt.plot(tout[0, :], xout[3, :, 2], label='time series 3')
p4, = plt.plot(tout[0, :], xout[4, :, 2], label='time series 4')
p5, = plt.plot(tout[0, :], xout[5, :, 2], label='time series 5')
p6, = plt.plot(tout[0, :], xout[6, :, 2], label='time series 6')
p7, = plt.plot(tout[0, :], xout[7, :, 2], label='time series 7')
p8, = plt.plot(tout[0, :], xout[8, :, 2], label='time series 8')
p9, = plt.plot(tout[0, :], xout[9, :, 2], label='time series 9')
p10, = plt.plot(tout[0, :], xout[10, :, 2], label='time series 10')
plt.legend(handles = [p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10], bbox_to_anchor = (1.05, 1), loc = 2, borderaxespad = 0.)
plt.title('Lorenz oscillator (z\')')
plt.show()